### PR TITLE
Test Enum implemented with IndexedBuiler and StringBuilder

### PR DESCRIPTION
**Pull request by zonca**
the changes in the compiler are in this related pull request: https://github.com/det-lab/kaitai_struct_compiler/pull/3/files

implements https://github.com/ManasviGoyal/kaitai_struct_awkward_runtime/issues/14

This includes also the debugging features that I am using heavily

- test: build compiler with debug symbols
- test: debug C++ files
- test: VS Code setup for C++ debugging
- test: make target to create cpp files for all test cases
- test: support debug build
- test: compile libraries in debug mode
- test: debug index_option by default
- test: use absolute path in the building process
- test: vscode build also source cpp
- test: update unit test to new implementation of enum
- feat: update compiler to enum implemented with indexed

### CODE REVIEW

**Comment by zonca** [comment]
## Difference on the layout for scdms

https://gist.github.com/zonca/4ae1109a9c6a3dc907a7245022ede5d2/revisions?diff=unified&w=

## for simple enum

https://gist.github.com/zonca/0c4ae4629ab5346629da2038323aa272/revisions

**Comment by zonca** [comment]
to understand if there is anything wrong with indexing, I tested with the usual https://github.com/ManasviGoyal/kaitai_struct_awkward_runtime/blob/303a4be92d1a85449d783052478110066594ac5b/example_data/schemas/simple_enum.ksy

I created a new data file with a length of 3:

```python
import numpy as np
np.array([3, 4, 2, 5, 1, 6], dtype="<u4").tofile("example_data/data/simple_enum.bin")
```

this is properly read by awkward-kaitai:

```python
In [21]: awkward_array.simple_enumA__Zn_triggers.v_one_trig_metaA__Ztrigger_id
Out[21]: <Array [[3, 2, 1]] type='1 * var * uint32'>
In [22]: awkward_array.simple_enumA__Zn_triggers.v_one_trig_metaA__Ztrigger_type
Out[22]: <Array [['eorr', 'bcr', 'borts']] type='1 * var * categorical[type=string]'>
```

I was expecting 1D arrays, can @jpivarski and @ManasviGoyal confirm 2D arrays are expected?

Then if I look at the layout:

```xml
<RecordArray is_tuple='false' len='1'>
    <content index='0' field='simple_enumA__Zn_triggers'>
        <ListOffsetArray len='1'>
            <offsets><Index dtype='int64' len='2'>[0 3]</Index></offsets>
            <content><RecordArray is_tuple='false' len='3'>
                <content index='0' field='v_one_trig_metaA__Ztrigger_id'>
                    <NumpyArray dtype='uint32' len='3'>[3 2 1]</NumpyArray>
                </content>
                <content index='1' field='v_one_trig_metaA__Ztrigger_type'>
                    <IndexedArray len='3'>
                        <parameter name='__array__'>'categorical'</parameter>
                        <index><Index dtype='uint32' len='3'>
                            [0 1 2]
                        </Index></index>
                        <content><ListOffsetArray len='3'>
                            <parameter name='__array__'>'string'</parameter>
                            <offsets><Index dtype='int64' len='4'>[ 0  4  7 12]</Index></offsets>
                            <content><NumpyArray dtype='uint8' len='12'>
                                <parameter name='__array__'>'char'</parameter>
                                [101 111 114 114  98  99 114  98 111 114 116
                                 115]
                            </NumpyArray></content>
                        </ListOffsetArray></content>
                    </IndexedArray>
                </content>
            </RecordArray></content>
        </ListOffsetArray>
    </content>
</RecordArray>
```

is the indexarray index expected to be `[0 1 2]`?

**Comment by zonca** [comment]
actually I am dubious that the offsets of the indexarray are correct:

```xml
<offsets><Index dtype='int64' len='4'>[ 0  4  7 12]</Index></offsets>
```

shouldn't it be `8` instead of `7`?

**Comment by ManasviGoyal** [comment]
> actually I am dubious that the offsets of the indexarray are correct:
> 
> ```
> <offsets><Index dtype='int64' len='4'>[ 0  4  7 12]</Index></offsets>
> ```
> 
> shouldn't it be `8` instead of `7`?

The offsets are correct. They correspond to the index of the strings. So for `'eorr'` - `0-3`, `'bcr'` - `4-6` `'borts'` - `7-11` and so on.

**Comment by ManasviGoyal** [comment]
> is the indexarray index expected to be `[0 1 2]`?

This is the part I am unsure about. According to my understanding, the index should be `[4 5 6]` according to the keys of the map. @jpivarski is that the case?

**Comment by jpivarski** [comment]
In Awkward, IndexedArray and IndexedOptionArray need their `index` to correspond to 0-indexed positions of the strings they represent in the `content`. If the original KSY enums are non-0-indexed values, like 

```
cat = 100
dog = 10
horse = 1
```

Then those would need to be mapped to 0-indexed values, to make a

```
<IndexedArray>
    <index>[0 2 1 0 0 2 2 0]</index>
    <content>
        <ListOffsetArray representing "cat", "dog", "horse" />
    <parameter name="__array__">categorical</parameter>
</IndexedArray>
```

(If something is labeled as categorical and the `content` he's not unique, pyarrow will segfault if you use a tries to convert such an array into Arrow. That would be a bad downstream consequence.)

You can't effectively reindex the 100, 10, 1 to 0, 1, 2 in Awkward Array because you can't put an Indexed(Option)Array inside of an Indexed(Option)Array. If any explicit remapping needs to be done, it needs to be done in C++ at runtime.

**Comment by zonca** [comment]
definitely there is a problem with the current implementation.
using the usual https://github.com/ManasviGoyal/kaitai_struct_awkward_runtime/blob/303a4be92d1a85449d783052478110066594ac5b/example_data/schemas/simple_enum.ksy

if I have a file with an enum used multiple times, like:

```python
np.array([0, 1]*4, dtype="<u4").tofile("example_data/data/simple_enum.bin")
```

it is interpreted as different values:

```xml
<RecordArray is_tuple='false' len='1'>
    <content index='0' field='simple_enumA__Zn_triggers'>
        <ListOffsetArray len='1'>
            <offsets><Index dtype='int64' len='2'>[0 4]</Index></offsets>
            <content><RecordArray is_tuple='false' len='4'>
                <content index='0' field='v_one_trig_metaA__Ztrigger_id'>
                    <NumpyArray dtype='uint32' len='4'>[0 0 0 0]</NumpyArray>
                </content>
                <content index='1' field='v_one_trig_metaA__Ztrigger_type'>
                    <IndexedArray len='4'>
                        <parameter name='__array__'>'categorical'</parameter>
                        <index><Index dtype='uint32' len='4'>[0 1 2 3]</Index></index>
                        <content><ListOffsetArray len='4'>
                            <parameter name='__array__'>'string'</parameter>
                            <offsets><Index dtype='int64' len='5'>[ 0  7 14 21 28]</Index></offsets>
                            <content><NumpyArray dtype='uint8' len='28'>
                                <parameter name='__array__'>'char'</parameter>
                                [112 104 121 115 105  99 115 112 104 121 115
                                 105  99 115 112 104 121 115 105  99 115 112
                                 104 121 115 105  99 115]
                            </NumpyArray></content>
                        </ListOffsetArray></content>
                    </IndexedArray>
                </content>
            </RecordArray></content>
        </ListOffsetArray>
    </content>
</RecordArray>
```

**Comment by zonca** [comment]
@ManasviGoyal if you know already how to fix what I mentioned above please let me know, otherwise I'll try to fix it myself.

**Comment by ManasviGoyal** [comment]
> @ManasviGoyal if you know already how to fix what I mentioned above please let me know, otherwise I'll try to fix it myself.

I am not sure how to do it right away. I'll have to figure it out. So you can go ahead and try to fix it. Thanks!

**Comment by zonca** [comment]
is there any example in awkward, for example in https://github.com/scikit-hep/awkward/blob/main/header-only/tests/test_1494-layout-builder.cpp of the kind of data structure we want to use to represent an `enum` field?

**Comment by ManasviGoyal** [comment]
> is there any example in awkward, for example in https://github.com/scikit-hep/awkward/blob/main/header-only/tests/test_1494-layout-builder.cpp of the kind of data structure we want to use to represent an `enum` field?

There is none for the C++ LayoutBuilder. There are many for the Python side like [this](https://github.com/scikit-hep/awkward/blob/main/tests/test_2630_akstr_to_categorical.py).

You can look for the `categorical` keyword in the `tests` directory to get a better idea.

**Comment by zonca** [comment]
ok, thanks @ManasviGoyal,
here is the structure we want to have:

```python
import awkward as ak
import numpy as np

categorical = ak.str.to_categorical(["", "physics", "physics", "borr", "borr", "physics"])

a = ak.Array({
    "n_triggers":
     {"trigger_id":np.arange(len(categorical), dtype=np.uint64),
      "trigger_type":categorical},

})

a.layout
```

so the output layout is:

```xml
<RecordArray is_tuple='false' len='6'>
    <content index='0' field='n_triggers'>
        <RecordArray is_tuple='false' len='6'>
            <content index='0' field='trigger_id'>
                <NumpyArray dtype='uint64' len='6'>[0 1 2 3 4 5]</NumpyArray>
            </content>
            <content index='1' field='trigger_type'>
                <IndexedArray len='6'>
                    <parameter name='__array__'>'categorical'</parameter>
                    <index><Index dtype='int64' len='6'>[0 1 1 2 2 1]</Index></index>
                    <content><ListOffsetArray len='3'>
                        <parameter name='__array__'>'string'</parameter>
                        <offsets><Index dtype='int64' len='4'>[ 0  0  7 11]</Index></offsets>
                        <content><NumpyArray dtype='uint8' len='11'>
                            <parameter name='__array__'>'char'</parameter>
                            [112 104 121 115 105  99 115  98 111 114 114]
                        </NumpyArray></content>
                    </ListOffsetArray></content>
                </IndexedArray>
            </content>
        </RecordArray>
    </content>
</RecordArray>
```

I added a value of `0` just to force awkward to use the indexing we want to use.
I'll work on implementing this and use this example as a test.

**Comment by zonca** [comment]
ok, for now I am working directly on the C++ code modifying it manually, if I get this working then I'll port to Scala.

See https://gist.github.com/zonca/8045dc6294e2b9ff4e053a339a3a77fb

with this I get the layout:

```xml
<RecordArray is_tuple='false' len='1'>
    <content index='0' field='simple_enumA__Zn_triggers'>
        <ListOffsetArray len='1'>
            <offsets><Index dtype='int64' len='2'>[0 4]</Index></offsets>
            <content><RecordArray is_tuple='false' len='4'>
                <content index='0' field='v_one_trig_metaA__Ztrigger_id'>
                    <NumpyArray dtype='uint32' len='4'>[0 0 0 0]</NumpyArray>
                </content>
                <content index='1' field='v_one_trig_metaA__Ztrigger_type'>
                    <IndexedArray len='4'>
                        <parameter name='__array__'>'categorical'</parameter>
                        <index><Index dtype='uint32' len='4'>[1 1 1 1]</Index></index>
                        <content><ListOffsetArray len='2'>
                            <parameter name='__array__'>'string'</parameter>
                            <offsets><Index dtype='int64' len='3'>[0 0 7]</Index></offsets>
                            <content><NumpyArray dtype='uint8' len='7'>
                                <parameter name='__array__'>'char'</parameter>
                                [112 104 121 115 105  99 115]
                            </NumpyArray></content>
                        </ListOffsetArray></content>
                    </IndexedArray>
                </content>
            </RecordArray></content>
        </ListOffsetArray>
    </content>
</RecordArray>
```

A surprising discovery is that Awkward automatically discards values in the string dictionary which are not used.
So for example here we are using only 1, so even if in the C++ code I set other 2 strings they are not visible in the layout.
Anyway, this seems fine, if I change the data file to display also 2 and 3 they are correctly displayed:

```xml
<RecordArray is_tuple='false' len='1'>
    <content index='0' field='simple_enumA__Zn_triggers'>
        <ListOffsetArray len='1'>
            <offsets><Index dtype='int64' len='2'>[0 6]</Index></offsets>
            <content><RecordArray is_tuple='false' len='6'>
                <content index='0' field='v_one_trig_metaA__Ztrigger_id'>
                    <NumpyArray dtype='uint32' len='6'>[0 0 0 0 0 0]</NumpyArray>
                </content>
                <content index='1' field='v_one_trig_metaA__Ztrigger_type'>
                    <IndexedArray len='6'>
                        <parameter name='__array__'>'categorical'</parameter>
                        <index><Index dtype='uint32' len='6'>[1 1 1 1 2 3]</Index></index>
                        <content><ListOffsetArray len='4'>
                            <parameter name='__array__'>'string'</parameter>
                            <offsets><Index dtype='int64' len='5'>[ 0  0  7 11 14]</Index></offsets>
                            <content><NumpyArray dtype='uint8' len='14'>
                                <parameter name='__array__'>'char'</parameter>
                                [112 104 121 115 105  99 115  98 111 114 114
                                 105 114 114]
                            </NumpyArray></content>
                        </ListOffsetArray></content>
                    </IndexedArray>
                </content>
            </RecordArray></content>
        </ListOffsetArray>
    </content>
</RecordArray>
```

Now the main error I get is that if I have an index array of 4 elements, at runtime it complaints that also the array of strings in stringbuilder needs to be 4 elements.
Which is really strange because in my test in Awkward Python, this was not a problem, see https://github.com/ManasviGoyal/kaitai_struct_awkward_runtime/pull/39#issuecomment-2061585984.

For example if I have only 4 elements in the stringbuilder:

```cpp

    std::map<int, std::string> trigger_types_t_map {
        {0, ""},
        {1, "physics"},
        {2, "borr"},
        {3, "irr"},
        //{4, "eorr"},
        //{5, "bcr"},
        // {6, "borts"},
        // {7, "eorts"},
    };
```

but 6 elements in the indexbuilder because I have created a data file:

    np.array([0, 1]*4+[0, 2,0,3], dtype="<u4").tofile("example_data/data/simple_enum.bin")

Then I get the error:

    RuntimeError: Indexed node4 has content length 4 but index has length 6

**Comment by zonca** [comment]
@ManasviGoyal @jpivarski I'm stuck on the error above, do you have suggestions? thanks

**Comment by jpivarski** [comment]
The `is_valid` constraints in LayoutBuilder.h are checking the wrong things.

* [Indexed::is_valid](https://github.com/scikit-hep/awkward/blob/ce6a21f1245bc320038ee20a5d403b7ee92beccd/header-only/layout-builder/awkward/LayoutBuilder.h#L1211-L1225) shouldn't complain about `content_.length() != index_.length()`. It should complain about `content_.length() <= ` the maximum value in `index_`.
* [IndexedOption::is_valid](https://github.com/scikit-hep/awkward/blob/ce6a21f1245bc320038ee20a5d403b7ee92beccd/header-only/layout-builder/awkward/LayoutBuilder.h#L1411-L1425) shouldn't complain about `content_.length() != last_valid_ + 1`. It should complain about `content_.length() <= ` the maximum non-negative value in `index_`.
* [Union::is_valid](https://github.com/scikit-hep/awkward/blob/ce6a21f1245bc320038ee20a5d403b7ee92beccd/header-only/layout-builder/awkward/LayoutBuilder.h#L2295-L2317) shouldn't complain about `lengths[tag] != last_valid_index_[tag] + 1`. It should complain about `lengths[tag] <= ` the maximum value in `index_`, considering only those `index_[i]` for which `tags_[i] == tag`.

(I checked all of the `is_valid` functions; the other ones all appear to be correct.)

These are designed to be $\mathcal{O}(1)$ checks, but they'll need running-maximum variables in order to stay $\mathcal{O}(1)$ (several variables in the case of `Union`). It looks like that's what `last_valid_` and `last_valid_index_` are, but they're tracking the wrong things: you don't want the _last_ value, you want the maximum or maximum non-negative value.

~~The source of truth for these conditions are on the [IndexedArray](https://awkward-array.org/doc/main/reference/generated/ak.contents.IndexedArray.html), [IndexedOptionArray](https://awkward-array.org/doc/main/reference/generated/ak.contents.IndexedOptionArray.html), and [UnionArray](https://awkward-array.org/doc/main/reference/generated/ak.contents.UnionArray.html) documentation pages... and I don't see the constraints correctly specified here, either. I'm going to fix that in scikit-hep/awkward#3076 now.~~

~~I also don't see the correct checks applied in [IndexedArray._validity_error](https://github.com/scikit-hep/awkward/blob/main/src/awkward/contents/indexedarray.py#L958-L976), [IndexedOptionArray._validity_error](https://github.com/scikit-hep/awkward/blob/main/src/awkward/contents/indexedoptionarray.py#L1492-L1512), and [UnionArray._validity_error](https://github.com/scikit-hep/awkward/blob/ce6a21f1245bc320038ee20a5d403b7ee92beccd/src/awkward/contents/unionarray.py#L1356-L1402). I don't understand it; these checks go way back to early development in Awkward Array and I'm sure they were explicit. I don't know how they would have just disappeared like this.~~

(Summary: the `is_valid` checks in LayoutBuilder.h were wrong, ~~but the correct validity checks are missing from the documentation and no such checks are performed in the Python code.~~)

Nevermind: I found it. I don't know why I couldn't see it; I was looking right at it.

In the [IndexedArray](https://awkward-array.org/doc/main/reference/generated/ak.contents.IndexedArray.html) documentation,

```python
        for x in index:
            assert 0 <= x < len(content)  # index[i] must not be negative
```

In the [IndexedOptionArray](https://awkward-array.org/doc/main/reference/generated/ak.contents.IndexedOptionArray.html) documentation,

```python
        for x in index:
            assert x < len(content)  # index[i] may be negative
```

And in the [UnionArray](https://awkward-array.org/doc/main/reference/generated/ak.contents.UnionArray.html) documentation,

```python
        for i, x in enumerate(tags):
            assert 0 <= index[i] < len(contents[x])
```

In the active code, the condition is checked by the [awkward_IndexedArray_validity](https://github.com/scikit-hep/awkward/blob/ce6a21f1245bc320038ee20a5d403b7ee92beccd/awkward-cpp/src/cpu-kernels/awkward_IndexedArray_validity.cpp#L7-L25) kernel for IndexedArray and IndexedOptionArray (controlled by the `isoption` flag) and the [awkward_UnionArray_validity](https://github.com/scikit-hep/awkward/blob/ce6a21f1245bc320038ee20a5d403b7ee92beccd/awkward-cpp/src/cpu-kernels/awkward_UnionArray_validity.cpp#L7-L32) kernel for UnionArray. Looking closely at these kernels, they do check for the right things. (They don't take the maximum and compare against the content length; they compare the content length against every value, but the result is the same.)

**Comment by zonca** [comment]
ok, I think this is now working for `simple_enum`.

Here are the generated C++ files: https://gist.github.com/zonca/f6d01c8bb388b4003ad77610b6887c76

The interface looks fine in Python:

```
In [2]: awkward_array.simple_enumA__Zn_triggers.v_one_trig_metaA__Ztrigger_type.to_list()
Out[2]: [['physics', 'physics', 'physics', 'physics', 'borr', 'irr']]
```

the layout:

```xml
<RecordArray is_tuple='false' len='1'>
    <content index='0' field='simple_enumA__Zn_triggers'>
        <ListOffsetArray len='1'>
            <offsets><Index dtype='int64' len='2'>[0 6]</Index></offsets>
            <content><RecordArray is_tuple='false' len='6'>
                <content index='0' field='v_one_trig_metaA__Ztrigger_id'>
                    <NumpyArray dtype='uint32' len='6'>[0 0 0 0 0 0]</NumpyArray>
                </content>
                <content index='1' field='v_one_trig_metaA__Ztrigger_type'>
                    <IndexedArray len='6'>
                        <parameter name='__array__'>'categorical'</parameter>
                        <index><Index dtype='uint32' len='6'>
                            [1 1 1 1 2 3]
                        </Index></index>
                        <content><ListOffsetArray len='4'>
                            <parameter name='__array__'>'string'</parameter>
                            <offsets><Index dtype='int64' len='5'>[ 0  4 11 15 18]</Index></offsets>
                            <content><NumpyArray dtype='uint8' len='18'>
                                <parameter name='__array__'>'char'</parameter>
                                [110 117 108 108 112 104 121 115 105  99 115
                                  98 111 114 114 105 114 114]
                            </NumpyArray></content>
                        </ListOffsetArray></content>
                    </IndexedArray>
                </content>
            </RecordArray></content>
        </ListOffsetArray>
    </content>
</RecordArray>
```

**Comment by zonca** [comment]
```
tests/test_animal.py .                                                   [ 10%]
tests/test_fake.py .                                                     [ 20%]
tests/test_hello_world.py .                                              [ 30%]
tests/test_index_option.py F                                             [ 40%]
tests/test_numpy.py .                                                    [ 50%]
tests/test_pixie4e.py .                                                  [ 60%]
tests/test_records.py .                                                  [ 70%]
tests/test_scdms.py F                                                    [ 80%]
tests/test_scdms_v8.py F                                                 [ 90%]
tests/test_simple_enum.py .                                              [100%]
```

the simple enum test runs fine also on github.
Next I was planning to check the scdms files, however  there is an unexpected failure in `index_option`, so I'll investigate that first.

**Comment by zonca** [comment]
@jpivarski the failure in index option is caused by the new implementation of `is_valid` 

https://github.com/scikit-hep/awkward/blob/e8c24829a9914ee179a05449aca1f2beb96e8fc9/header-only/layout-builder/awkward/LayoutBuilder.h#L1455-L1466

the error is:

    FAILED tests/test_index_option.py::test_index_option - RuntimeError: IndexedOption node4 has index 0 but content has length 0

it is probably due to the fact that while the definition of the file has both bank 16 and bank 32 https://github.com/det-lab/kaitai_struct_awkward_runtime/blob/main/example_data/schemas/index_option.ksy,
the file only has one of them, so the other is empty.

**Comment by zonca** [comment]
the changes in the compiler are in this related pull request: https://github.com/det-lab/kaitai_struct_compiler/pull/3/files

**Comment by zonca** [comment]
gist.github.com/5920274ed2da6bd8fce62afedfcea7dd

**Comment by zonca** [comment]
gist.github.com/5027109781e8b0668dd86c4c5d2d2176

**Comment by zonca** [comment]
Good news, @ManasviGoyal and I figured out the problem with `index_option` and created a fix for awkward: https://github.com/scikit-hep/awkward/pull/3120

The failing tests for the 2 scdms files were just due to the fact that the enums are now strings:

https://gist.github.com/zonca/5920274ed2da6bd8fce62afedfcea7dd/revisions
https://gist.github.com/zonca/5027109781e8b0668dd86c4c5d2d2176/revisions

so they are fine! This is completed

**Pull request merged**
