### PR TITLE
Test: fix index option test file

### PR DESCRIPTION
**Pull request by zonca**
See https://github.com/ManasviGoyal/kaitai_struct_compiler/pull/4#issuecomment-1968157980

### CODE REVIEW

**Comment by zonca** [comment]
it seems to me that when you parse a file which does not contain `bank1`, there should not be any data structure there, instead awkward-kaitai creates:

https://github.com/ManasviGoyal/kaitai_struct_awkward_runtime/blob/011c32febf4894f763c3b69ab723ffd9df4896ef/tests/test_index_option.py#L23-L29

**Comment by zonca** [comment]
Looking at the `ksy`, https://github.com/ManasviGoyal/kaitai_struct_awkward_runtime/blob/main/example_data/schemas/index_option.ksy
it is difficult to understand why `bank2` is a masked array. What is the reason?
 
https://github.com/ManasviGoyal/kaitai_struct_awkward_runtime/blob/011c32febf4894f763c3b69ab723ffd9df4896ef/tests/test_index_option.py#L36-L45

**Comment by ManasviGoyal** [comment]
> it seems to me that when you parse a file which does not contain `bank1`, there should not be any data structure there, instead awkward-kaitai creates:
> 
> https://github.com/ManasviGoyal/kaitai_struct_awkward_runtime/blob/011c32febf4894f763c3b69ab723ffd9df4896ef/tests/test_index_option.py#L23-L29

The data structure is created before we pass the data, in this case `bank1` will be a `IndexedOptionBuilder` with `None` value

**Comment by ManasviGoyal** [comment]
> Looking at the `ksy`, https://github.com/ManasviGoyal/kaitai_struct_awkward_runtime/blob/main/example_data/schemas/index_option.ksy it is difficult to understand why `bank2` is a masked array. What is the reason?
> 
> https://github.com/ManasviGoyal/kaitai_struct_awkward_runtime/blob/011c32febf4894f763c3b69ab723ffd9df4896ef/tests/test_index_option.py#L36-L45

It is because `bank2` is an `IndexedOptionBuilder` I think.

**Comment by zonca** [comment]
ok @ManasviGoyal, then this pull request could be merged

**Comment by zonca** [comment]
However, if I compare with what the standard kaitai struct does for Python, their structure is a lot simpler.
There is no `bank1` in the API and `bank2` has a very simple object structure:

```
In [17]: indexoption.bank2
Out[17]: <index_option.IndexOption.Bank32 at 0x7fc5c7c7fc10>

In [18]: indexoption.bank1
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[18], line 1
----> 1 indexoption.bank1

AttributeError: 'IndexOption' object has no attribute 'bank1'

In [19]: indexoption.bank2.name
Out[19]: 'Bank'

In [20]: indexoption.bank2.size
Out[20]: 2

In [21]: indexoption.bank2.type
Out[21]: 3
```

I would have expected something similar from `awkward-kaitai` as well, except when there are arrays which should be interpreted as awkward arrays.

For my reference: https://gist.github.com/zonca/2b8897ee76c8f17afb8b46403eb0964c

**Comment by ManasviGoyal** [comment]
> However, if I compare with what the standard kaitai struct does for Python, their structure is a lot simpler. There is no `bank1` in the API and `bank2` has a very simple object structure:
> 
> ```
> In [17]: indexoption.bank2
> Out[17]: <index_option.IndexOption.Bank32 at 0x7fc5c7c7fc10>
> 
> In [18]: indexoption.bank1
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[18], line 1
> ----> 1 indexoption.bank1
> 
> AttributeError: 'IndexOption' object has no attribute 'bank1'
> 
> In [19]: indexoption.bank2.name
> Out[19]: 'Bank'
> 
> In [20]: indexoption.bank2.size
> Out[20]: 2
> 
> In [21]: indexoption.bank2.type
> Out[21]: 3
> ```
> 
> I would have expected something similar from `awkward-kaitai` as well, except when there are arrays which should be interpreted as awkward arrays.
> 
> For my reference: https://gist.github.com/zonca/2b8897ee76c8f17afb8b46403eb0964c

Since we are using the `LayoutBuilder`, we need to prepare the form for the entire structure. So we need to have both `bank1` and `bank2` for `IndexOptionBuilder `. We may use `UnionBuilder`  if we only want `bank2` but it is a bit more complicated to implement. Maybe this can be tried later.

**Review by ManasviGoyal — APPROVED** [review]

**Pull request merged**
